// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//
package com.example.mixed_fragments_on_fragment.fragment

import com.apollographql.apollo.api.GraphqlFragment
import com.apollographql.apollo.api.ResponseField
import com.apollographql.apollo.api.ResponseFieldMarshaller
import com.apollographql.apollo.api.ResponseReader
import com.example.mixed_fragments_on_fragment.type.CustomType
import kotlin.Array
import kotlin.String
import kotlin.Suppress

@Suppress("NAME_SHADOWING", "UNUSED_ANONYMOUS_PARAMETER", "LocalVariableName",
    "RemoveExplicitTypeArguments", "NestedLambdaShadowedImplicitParameter")
data class CharacterDetails(
  val __typename: String = "Character",
  /**
   * The ID of the character
   */
  val id: String
) : GraphqlFragment {
  override fun marshaller(): ResponseFieldMarshaller = ResponseFieldMarshaller { writer ->
    writer.writeString(RESPONSE_FIELDS[0], this@CharacterDetails.__typename)
    writer.writeCustom(RESPONSE_FIELDS[1] as ResponseField.CustomTypeField,
        this@CharacterDetails.id)
  }

  companion object {
    private val RESPONSE_FIELDS: Array<ResponseField> = arrayOf(
        ResponseField.forString("__typename", "__typename", null, false, null),
        ResponseField.forCustomType("id", "id", null, false, CustomType.ID, null)
        )

    val FRAGMENT_DEFINITION: String = """
        |fragment CharacterDetails on Character {
        |  __typename
        |  id
        |}
        """.trimMargin()

    operator fun invoke(reader: ResponseReader): CharacterDetails = reader.run {
      val __typename = readString(RESPONSE_FIELDS[0])
      val id = readCustomType<String>(RESPONSE_FIELDS[1] as ResponseField.CustomTypeField)
      CharacterDetails(
        __typename = __typename,
        id = id
      )
    }
  }
}
