// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//
package com.example.mixed_fragments_on_fragment.fragment;

import com.apollographql.apollo.api.GraphqlFragment;
import com.apollographql.apollo.api.ResponseField;
import com.apollographql.apollo.api.ResponseFieldMapper;
import com.apollographql.apollo.api.ResponseFieldMarshaller;
import com.apollographql.apollo.api.ResponseReader;
import com.apollographql.apollo.api.ResponseWriter;
import com.apollographql.apollo.api.internal.Optional;
import com.apollographql.apollo.api.internal.Utils;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Arrays;
import java.util.Collections;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

public interface FriendDetails extends GraphqlFragment {
  String FRAGMENT_DEFINITION = "fragment FriendDetails on Character {\n"
      + "  __typename\n"
      + "  ...CharacterDetails\n"
      + "  ... on Human {\n"
      + "    homePlanet\n"
      + "  }\n"
      + "  ... on Droid {\n"
      + "    primaryFunction\n"
      + "  }\n"
      + "}";

  @NotNull String __typename();

  ResponseFieldMarshaller marshaller();

  default <T> T visit(Visitor<T> visitor) {
    if (this instanceof AsHuman) {
      return visitor.visit((AsHuman) this);
    } else if (this instanceof AsDroid) {
      return visitor.visit((AsDroid) this);
    } else if (this instanceof AsCharacter) {
      return visitor.visit((AsCharacter) this);
    }
    return visitor.visitDefault(this);
  }

  final class Mapper implements ResponseFieldMapper<FriendDetails> {
    static final ResponseField[] $responseFields = {
      ResponseField.forFragment("__typename", "__typename", Arrays.<ResponseField.Condition>asList(
        ResponseField.Condition.typeCondition(new String[] {"Human"})
      )),
      ResponseField.forFragment("__typename", "__typename", Arrays.<ResponseField.Condition>asList(
        ResponseField.Condition.typeCondition(new String[] {"Droid"})
      ))
    };

    final AsHuman.Mapper asHumanFieldMapper = new AsHuman.Mapper();

    final AsDroid.Mapper asDroidFieldMapper = new AsDroid.Mapper();

    final AsCharacter.Mapper asCharacterFieldMapper = new AsCharacter.Mapper();

    @Override
    public FriendDetails map(ResponseReader reader) {
      final AsHuman asHuman = reader.readFragment($responseFields[0], new ResponseReader.ObjectReader<AsHuman>() {
        @Override
        public AsHuman read(ResponseReader reader) {
          return asHumanFieldMapper.map(reader);
        }
      });
      if (asHuman != null) {
        return asHuman;
      }
      final AsDroid asDroid = reader.readFragment($responseFields[1], new ResponseReader.ObjectReader<AsDroid>() {
        @Override
        public AsDroid read(ResponseReader reader) {
          return asDroidFieldMapper.map(reader);
        }
      });
      if (asDroid != null) {
        return asDroid;
      }
      return asCharacterFieldMapper.map(reader);
    }
  }

  interface Visitor<T> {
    T visitDefault(@NotNull FriendDetails friendDetails);

    T visit(@NotNull AsHuman asHuman);

    T visit(@NotNull AsDroid asDroid);

    T visit(@NotNull AsCharacter asCharacter);
  }

  class AsHuman implements FriendDetails {
    static final ResponseField[] $responseFields = {
      ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("homePlanet", "homePlanet", null, true, Collections.<ResponseField.Condition>emptyList())
    };

    final @NotNull String __typename;

    final Optional<String> homePlanet;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public AsHuman(@NotNull String __typename, @Nullable String homePlanet) {
      this.__typename = Utils.checkNotNull(__typename, "__typename == null");
      this.homePlanet = Optional.fromNullable(homePlanet);
    }

    public @NotNull String __typename() {
      return this.__typename;
    }

    /**
     * The home planet of the human, or null if unknown
     */
    public Optional<String> homePlanet() {
      return this.homePlanet;
    }

    @SuppressWarnings("unchecked")
    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeString($responseFields[0], __typename);
          writer.writeString($responseFields[1], homePlanet.isPresent() ? homePlanet.get() : null);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "AsHuman{"
          + "__typename=" + __typename + ", "
          + "homePlanet=" + homePlanet
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof AsHuman) {
        AsHuman that = (AsHuman) o;
        return this.__typename.equals(that.__typename)
         && this.homePlanet.equals(that.homePlanet);
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= __typename.hashCode();
        h *= 1000003;
        h ^= homePlanet.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<AsHuman> {
      @Override
      public AsHuman map(ResponseReader reader) {
        final String __typename = reader.readString($responseFields[0]);
        final String homePlanet = reader.readString($responseFields[1]);
        return new AsHuman(__typename, homePlanet);
      }
    }
  }

  class AsDroid implements FriendDetails {
    static final ResponseField[] $responseFields = {
      ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("primaryFunction", "primaryFunction", null, true, Collections.<ResponseField.Condition>emptyList())
    };

    final @NotNull String __typename;

    final Optional<String> primaryFunction;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public AsDroid(@NotNull String __typename, @Nullable String primaryFunction) {
      this.__typename = Utils.checkNotNull(__typename, "__typename == null");
      this.primaryFunction = Optional.fromNullable(primaryFunction);
    }

    public @NotNull String __typename() {
      return this.__typename;
    }

    /**
     * This droid's primary function
     */
    public Optional<String> primaryFunction() {
      return this.primaryFunction;
    }

    @SuppressWarnings("unchecked")
    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeString($responseFields[0], __typename);
          writer.writeString($responseFields[1], primaryFunction.isPresent() ? primaryFunction.get() : null);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "AsDroid{"
          + "__typename=" + __typename + ", "
          + "primaryFunction=" + primaryFunction
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof AsDroid) {
        AsDroid that = (AsDroid) o;
        return this.__typename.equals(that.__typename)
         && this.primaryFunction.equals(that.primaryFunction);
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= __typename.hashCode();
        h *= 1000003;
        h ^= primaryFunction.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<AsDroid> {
      @Override
      public AsDroid map(ResponseReader reader) {
        final String __typename = reader.readString($responseFields[0]);
        final String primaryFunction = reader.readString($responseFields[1]);
        return new AsDroid(__typename, primaryFunction);
      }
    }
  }

  class AsCharacter implements FriendDetails {
    static final ResponseField[] $responseFields = {
      ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList())
    };

    final @NotNull String __typename;

    private final @NotNull Fragments fragments;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public AsCharacter(@NotNull String __typename, @NotNull Fragments fragments) {
      this.__typename = Utils.checkNotNull(__typename, "__typename == null");
      this.fragments = Utils.checkNotNull(fragments, "fragments == null");
    }

    public @NotNull String __typename() {
      return this.__typename;
    }

    public @NotNull Fragments fragments() {
      return this.fragments;
    }

    @SuppressWarnings("unchecked")
    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeString($responseFields[0], __typename);
          fragments.marshaller().marshal(writer);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "AsCharacter{"
          + "__typename=" + __typename + ", "
          + "fragments=" + fragments
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof AsCharacter) {
        AsCharacter that = (AsCharacter) o;
        return this.__typename.equals(that.__typename)
         && this.fragments.equals(that.fragments);
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= __typename.hashCode();
        h *= 1000003;
        h ^= fragments.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static class Fragments {
      final @NotNull CharacterDetails characterDetails;

      private transient volatile String $toString;

      private transient volatile int $hashCode;

      private transient volatile boolean $hashCodeMemoized;

      public Fragments(@NotNull CharacterDetails characterDetails) {
        this.characterDetails = Utils.checkNotNull(characterDetails, "characterDetails == null");
      }

      public @NotNull CharacterDetails characterDetails() {
        return this.characterDetails;
      }

      public ResponseFieldMarshaller marshaller() {
        return new ResponseFieldMarshaller() {
          @Override
          public void marshal(ResponseWriter writer) {
            writer.writeFragment(characterDetails.marshaller());
          }
        };
      }

      @Override
      public String toString() {
        if ($toString == null) {
          $toString = "Fragments{"
            + "characterDetails=" + characterDetails
            + "}";
        }
        return $toString;
      }

      @Override
      public boolean equals(Object o) {
        if (o == this) {
          return true;
        }
        if (o instanceof Fragments) {
          Fragments that = (Fragments) o;
          return this.characterDetails.equals(that.characterDetails);
        }
        return false;
      }

      @Override
      public int hashCode() {
        if (!$hashCodeMemoized) {
          int h = 1;
          h *= 1000003;
          h ^= characterDetails.hashCode();
          $hashCode = h;
          $hashCodeMemoized = true;
        }
        return $hashCode;
      }

      public static final class Mapper implements ResponseFieldMapper<Fragments> {
        static final ResponseField[] $responseFields = {
          ResponseField.forFragment("__typename", "__typename", Arrays.<ResponseField.Condition>asList(
            ResponseField.Condition.typeCondition(new String[] {"Human", "Droid"})
          ))
        };

        final CharacterDetails.Mapper characterDetailsFieldMapper = new CharacterDetails.Mapper();

        @Override
        public @NotNull Fragments map(ResponseReader reader) {
          final CharacterDetails characterDetails = reader.readFragment($responseFields[0], new ResponseReader.ObjectReader<CharacterDetails>() {
            @Override
            public CharacterDetails read(ResponseReader reader) {
              return characterDetailsFieldMapper.map(reader);
            }
          });
          return new Fragments(characterDetails);
        }
      }
    }

    public static final class Mapper implements ResponseFieldMapper<AsCharacter> {
      final Fragments.Mapper fragmentsFieldMapper = new Fragments.Mapper();

      @Override
      public AsCharacter map(ResponseReader reader) {
        final String __typename = reader.readString($responseFields[0]);
        final Fragments fragments = fragmentsFieldMapper.map(reader);
        return new AsCharacter(__typename, fragments);
      }
    }
  }
}
